version: '3.1'
services:
#  # https://hub.docker.com/_/mysql?tab=description
#  mysql8:
#    image: mysql:8.0.33
##    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    ports:
##      - 3306:3306
#       - "3308:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: takeaway
#      MYSQL_USER: takeaway
#      MYSQL_PASSWORD: takeaway
#      MYSQL_DATABASE: takeaway
#    volumes:
#      - /var/takeaway/mysql:/var/lib/mysql
  # https://registry.hub.docker.com/_/postgres
  postgres:
    image: postgres:15
    container_name: postgres15
    restart: always
    environment:
      POSTGRES_USER: takeaway
      POSTGRES_PASSWORD: takeaway
    ports:
      - "5432:5432"
#    volumes:
#      - /data/compose/postgresql/data:/var/lib/postgresql/data
  # https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
  pgadmin4:
    image: dpage/pgadmin4:7.3
    container_name: pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: sothereer@gmail.com
      PGADMIN_DEFAULT_PASSWORD: takeaway
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "54328:80"
##  https://min.io/docs/minio/linux/reference/minio-server/minio-server.html#id5
#  minio:
#    image: minio/minio:RELEASE.2023-06-29T05-12-28Z
#    container_name: minio
#    restart: on-failure
#    environment:
#      MINIO_ROOT_USER: takeaway
#      MINIO_ROOT_PASSWORD: takeaway
#      MINIO_API_ROOT_ACCESS: on
#      MINIO_ACCESS_KEY: takeaway
#      MINIO_SECRET_KEY: takeaway
#
#      DIRECTORIES: "/var/minio"
#    ports:
#      - "9090"
##  https://hub.docker.com/_/nginx
#  nginx:
#    image: nginx:stable-alpine3.17-slim
#    container_name: nginx


