version: '3.1'
services:
#  # https://hub.docker.com/_/mysql?tab=description
#  mysql8:
#    image: mysql:8.0.33
##    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    ports:
##      - 3306:3306
#       - "3308:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: takeaway
#      MYSQL_USER: takeaway
#      MYSQL_PASSWORD: takeaway
#      MYSQL_DATABASE: takeaway
#    volumes:
#      - /var/takeaway/mysql:/var/lib/mysql
  # https://registry.hub.docker.com/_/postgres
  postgres:
    image: postgres:15
    container_name: postgres15
    restart: always
    environment:
      POSTGRES_USER: takeaway
      POSTGRES_PASSWORD: takeaway
    ports:
      - "5432:5432"
#    volumes:
#      - /data/compose/postgresql/data:/var/lib/postgresql/data
  # https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
  pgadmin4:
    image: dpage/pgadmin4:7.3
    container_name: pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: sothereer@gmail.com
      PGADMIN_DEFAULT_PASSWORD: takeaway
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "54328:80"



