version: '3.1'
services:
  # https://hub.docker.com/_/mysql?tab=description
  mysql8:
    image: mysql:8.0.33
#    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
#      - 3306:3306
       - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: takeaway
      MYSQL_USER: takeaway
      MYSQL_PASSWORD: takeaway
      MYSQL_DATABASE: takeaway
    volumes:
      - /var/takeaway/mysql:/var/lib/mysql